export const TYPES = {
    ENVIRONMENTAL_CONFIG: Symbol.for('ENVIRONMENTAL_CONFIG'),
    EXPRESS: Symbol.for('EXPRESS'),
    MONGO_DB_CLIENT: Symbol.for('MONGO_DB_CLIENT'),
    HASH_GENERATOR: Symbol.for('HASH_GENERATOR'),
    EMAIL_CREATOR: Symbol.for('EMAIL_CREATOR')
};
